import { VideoData } from './types';

// Using Google's sample videos which are highly reliable and persistent
export const MOCK_VIDEOS: VideoData[] = [
  {
    id: '1',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    username: '@nature_lover',
    description: 'The waves are mesmerizing today 🌊 #ocean #vibes',
    song: 'Original Sound - Nature Sounds',
    likes: 12400,
    comments: 342,
    shares: 1200,
    avatar: 'https://picsum.photos/100/100?random=1',
  },
  {
    id: '2',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    username: '@urban_explorer',
    description: 'City lights at night never get old 🌃 #citylife',
    song: 'Midnight City - M83 (Remix)',
    likes: 8500,
    comments: 120,
    shares: 540,
    avatar: 'https://picsum.photos/100/100?random=2',
  },
  {
    id: '3',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    username: '@skater_girl',
    description: 'Cruising down the street 🛹 #skate',
    song: 'Sk8er Boi - Avril Lavigne',
    likes: 45000,
    comments: 2300,
    shares: 8900,
    avatar: 'https://picsum.photos/100/100?random=3',
  },
  {
    id: '4',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    username: '@coffee_addict',
    description: 'Fresh beans for the morning brew ☕️ #coffee',
    song: 'Morning Jazz - Relax',
    likes: 5600,
    comments: 89,
    shares: 200,
    avatar: 'https://picsum.photos/100/100?random=4',
  },
  {
    id: '5',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    username: '@fitness_junkie',
    description: 'No days off! Let’s get it 💪 #gymtok',
    song: 'Eye of the Tiger - Survivor',
    likes: 22100,
    comments: 560,
    shares: 1100,
    avatar: 'https://picsum.photos/100/100?random=5',
  }
];

export const MOCK_ESPORTS_VIDEOS: VideoData[] = [
  {
    id: 'e1',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    username: '@pro_gamer_1',
    description: 'Insane clutch in the grand finals! 🎮 🏆 #esports',
    song: 'Victory Theme - Gaming',
    likes: 50000,
    comments: 1200,
    shares: 3400,
    avatar: 'https://picsum.photos/100/100?random=10',
  },
  {
    id: 'e2',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    username: '@league_champ',
    description: 'Highlight reel from today stream 🔴 #live',
    song: 'Stream Beats',
    likes: 23000,
    comments: 800,
    shares: 1500,
    avatar: 'https://picsum.photos/100/100?random=11',
  },
  {
    id: 'e3',
    url: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    username: '@fps_god',
    description: 'Can’t believe I hit that shot 🎯 #sniper',
    song: 'Precision - Dubstep',
    likes: 89000,
    comments: 4500,
    shares: 12000,
    avatar: 'https://picsum.photos/100/100?random=12',
  }
];